using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// Inventory System -- Item
/// </summary>

[System.Serializable]
public class InvItem
{
	public enum Slot
	{
		None,		// First element MUST be 'None'
		Weapon,		// All the following elements are yours to customize -- edit, add or remove as you desire
		Shield,
		Body,
		Shoulders,
		Bracers,
		Boots,
		Trinket,
	}

	/// <summary>
	/// 16-bit item ID, generated by the system.
	/// Not to be confused with a 32-bit item ID, which actually contains the ID of the database as its prefix.
	/// </summary>

	public int id16;

	/// <summary>
	/// Name of this item.
	/// </summary>

	public string name;

	/// <summary>
	/// This item's custom description.
	/// </summary>

	public string description;

	/// <summary>
	/// Slot that this item belongs to.
	/// </summary>

	public Slot slot = Slot.None;

	/// <summary>
	/// And and all stats this item may have.
	/// </summary>

	public List<InvStat> stats = new List<InvStat>();

	/// <summary>
	/// Game Object that will be created and attached to the specified slot on the body.
	/// This should typically be a prefab with a renderer component, such as a sword,
	/// a bracer, shield, etc.
	/// </summary>

	public GameObject attachment;

	/// <summary>
	/// Object's main material color.
	/// </summary>

	public Color color = Color.white;
}